#!/usr/bin/env bash


build()
{
    ./build wintux $1
    ./build web $1
}

build basic_editor
build endless_grid
build line_renderer
build metroidvania
build MJ172_Security
build new_ui
build remake_renderer
build rr_matrices

