:: This requires VISUALSTUDIOPATH to be defined but at least I can stop thinking about it once it is setup on all my systems....

call "%VISUALSTUDIOPATH%\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64 
