#!/bin/bash

if [ $1 == "web" ] 
then
    emrun ./_build/web/$2/index.html
fi

if [ $1 == "wintux" ] 
then
    wine _build/win32/$2/a.exe
fi

if [ $1 == "tux" ] 
then
    ./_build/tux/$2/$2
fi


if [ $1 == "sdl" ] 
then
    ./_build/sdltux/$2/$2
fi
