#include "angelscript/include/angelscript.h"

#include "angelscript/source/as_atomic.cpp"
#include "angelscript/source/as_builder.cpp"
#include "angelscript/source/as_bytecode.cpp"

#include "angelscript/source/as_callfunc.cpp"
#include "angelscript/source/as_callfunc_arm.cpp"
#include "angelscript/source/as_callfunc_arm64.cpp"
#include "angelscript/source/as_callfunc_mips.cpp"
#include "angelscript/source/as_callfunc_ppc.cpp"
#include "angelscript/source/as_callfunc_ppc_64.cpp"
#include "angelscript/source/as_callfunc_riscv64.cpp"
#include "angelscript/source/as_callfunc_sh4.cpp"
#include "angelscript/source/as_callfunc_x86.cpp"
#include "angelscript/source/as_callfunc_x64_gcc.cpp"
#include "angelscript/source/as_callfunc_x64_mingw.cpp"

#include "angelscript/source/as_compiler.cpp"
#include "angelscript/source/as_context.cpp"
#include "angelscript/source/as_configgroup.cpp"
#include "angelscript/source/as_datatype.cpp"
#include "angelscript/source/as_generic.cpp"
#include "angelscript/source/as_gc.cpp"
#include "angelscript/source/as_globalproperty.cpp"
#include "angelscript/source/as_memory.cpp"
#include "angelscript/source/as_module.cpp"
#include "angelscript/source/as_objecttype.cpp"
#include "angelscript/source/as_outputbuffer.cpp"
#include "angelscript/source/as_parser.cpp"
#include "angelscript/source/as_restore.cpp"
#include "angelscript/source/as_scriptcode.cpp"
#include "angelscript/source/as_scriptengine.cpp"
#include "angelscript/source/as_scriptfunction.cpp"
#include "angelscript/source/as_scriptnode.cpp"
#include "angelscript/source/as_scriptobject.cpp"
#include "angelscript/source/as_string.cpp"
#include "angelscript/source/as_string_util.cpp"
#include "angelscript/source/as_thread.cpp"
#include "angelscript/source/as_tokenizer.cpp"
#include "angelscript/source/as_typeinfo.cpp"
#include "angelscript/source/as_variablescope.cpp"

