
#include "main/main.c"

#include "private/common/nl_audio_openal.c"
#include "private/common/nl_camera.c"
#include "private/common/nl_fileio.c"
#include "private/common/nl_input.c"
#include "private/common/nl_math.c"
#include "private/common/nl_memory.c"
#include "private/common/nl_random.c"

#include "private/gl/nl_gl_linux.c"
#include "private/gl/nl_mesh_gl.c"
#include "private/gl/nl_renderer_gl_common.c"
#include "private/gl/nl_renderer_gl_linux.c"
#include "private/gl/nl_shader.c"
#include "private/gl/nl_vertex_attrib_gl.c"
#include "third_party/stb_image.c"
#include "private/linux/nl_window_linux.c"
#include "private/linux/nl_deltatime_linux.c"
